#!/bin/bash

QuickAddRunning=`ps -A | grep "QuickAdd*" | grep -v "grep"`
DaemonRunning=`ps -A | grep "finish_Install.sh" | grep -v "grep"`


if [ -z ${QuickAddRunning} ] && [ -z ${DaemonRunning} ]; then
	echo "Checking for core-apps"
	/usr/local/bin/jamf policy -event Core-Apps
    /usr/local/bin/jamf policy -event OA-Apps
    /usr/local/bin/jamf policy -event Sch-Apps
    /usr/local/bin/jamf policy -event MS-UP
else
	echo "QuickAdd package or Daemon is running, exiting this core-apps check"
    exit 1;
fi

exit 0;
