#!/bin/bash

###################################################################
#
# Script to add applications  to the dock.
# Utilises - https://github.com/kcrawford/dockutil
#
# Last Changed: "Thu  2 Aug 2018 14:37:21 BST"
# Version: 0.4
# Origin: https://github.com/UoE-macOS/
# Released by JSS User: ganders1
#
##################################################################


ACTIVE_USER=`python -c 'from SystemConfiguration import SCDynamicStoreCopyConsoleUser; import sys; username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]; username = [username,""][username in [u"loginwindow", None, u""]]; sys.stdout.write(username + "\n");'`


echo "Active user is $ACTIVE_USER"

if [ -z "${ACTIVE_USER}" ] || [ "${ACTIVE_USER}" == "root" ] || [ "${ACTIVE_USER}" == "" ]; then
exit 0;
fi

# we need to wait for the dock to actually start if a user is present
until [[ $(pgrep Dock) ]]; do
    wait
done

DOCK_PREF="/Users/$ACTIVE_USER/Library/Preferences/com.apple.dock.plist"

# Set the path for the dock command line tool.
DOCK_UTIL="/usr/local/bin/dockutil"

if [ -d "/Applications/Microsoft Word.app" ]; then
	$DOCK_UTIL --add "/Applications/Microsoft Word.app" --no-restart $DOCK_PREF
fi

if [ -d "/Applications/Microsoft Excel.app" ]; then
	$DOCK_UTIL --add "/Applications/Microsoft Excel.app" --no-restart $DOCK_PREF
fi

if [ -d "/Applications/Microsoft Powerpoint.app" ]; then
	$DOCK_UTIL --add "/Applications/Microsoft Powerpoint.app" --no-restart $DOCK_PREF
fi

if [ -d "/Applications/Microsoft OneNote.app" ]; then
	$DOCK_UTIL --add "/Applications/Microsoft OneNote.app" --no-restart $DOCK_PREF
fi

if [ -d "/Library/MacSD/Applications" ]; then
	# Make sure the icon is set
	python -c 'import Cocoa; Cocoa.NSWorkspace.sharedWorkspace().setIcon_forFile_options_(Cocoa.NSImage.alloc().initWithContentsOfFile_("/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/ApplicationsFolderIcon.icns"), "/Library/MacSD/Applications", 0)'
	# Add the dir to the dock
	$DOCK_UTIL --add "/Library/MacSD/Applications" --view list --display folder --sort name --no-restart $DOCK_PREF
fi

# Generate web links for OneDrive and Outlook and add them to the Dock

OneDriveURL="/Library/MacSD/Office 365 OneDrive.url"
echo '[InternetShortcut]' > "$OneDriveURL"
echo -n 'URL=' >> "$OneDriveURL"
echo "https://uoe-my.sharepoint.com/personal/${ACTIVE_USER}_ed_ac_uk" >> "$OneDriveURL"
python -c 'import Cocoa; Cocoa.NSWorkspace.sharedWorkspace().setIcon_forFile_options_(Cocoa.NSImage.alloc().initWithContentsOfFile_("/usr/local/jamf/onedrive.png"), "/Library/MacSD/Office 365 OneDrive.url", 0)'
$DOCK_UTIL --add "$OneDriveURL" --section others --no-restart $DOCK_PREF

OutlookURL="/Library/MacSD/Office 365 Email.url"
echo '[InternetShortcut]' > "$OutlookURL"
echo -n 'URL=' >> "$OutlookURL"
echo https://outlook.com/ed.ac.uk/ >> "$OutlookURL"
python -c 'import Cocoa; Cocoa.NSWorkspace.sharedWorkspace().setIcon_forFile_options_(Cocoa.NSImage.alloc().initWithContentsOfFile_("/Applications/Microsoft Outlook.app/Contents/Resources/Outlook.icns"), "/Library/MacSD/Office 365 Email.url", 0)'
$DOCK_UTIL --add "$OutlookURL" --section others --no-restart $DOCK_PREF

HelpURL="/Library/MacSD/Help & Support.url"
echo '[InternetShortcut]' > "$HelpURL"
echo -n 'URL=' >> "$HelpURL"
echo https://www.ed.ac.uk/is/it-help >> "$HelpURL"
python -c 'import Cocoa; Cocoa.NSWorkspace.sharedWorkspace().setIcon_forFile_options_(Cocoa.NSImage.alloc().initWithContentsOfFile_("/Applications/Support.app/Contents/Resources/appIcon.icns"), "/Library/MacSD/Help & Support.url", 0)'
$DOCK_UTIL --add "$HelpURL" --section others --no-restart $DOCK_PREF


# Remove additional Dock items.
$DOCK_UTIL --remove "Siri" --no-restart $DOCK_PREF
$DOCK_UTIL --remove "Mail" --no-restart $DOCK_PREF
$DOCK_UTIL --remove "Contacts" --no-restart $DOCK_PREF
$DOCK_UTIL --remove "Calendar" --no-restart $DOCK_PREF
$DOCK_UTIL --remove "Notes" --no-restart $DOCK_PREF
$DOCK_UTIL --remove "Reminders" --no-restart $DOCK_PREF
$DOCK_UTIL --remove "Maps" --no-restart $DOCK_PREF
$DOCK_UTIL --remove "Photos" --no-restart $DOCK_PREF
$DOCK_UTIL --remove "Messages" --no-restart $DOCK_PREF
$DOCK_UTIL --remove "FaceTime"	--no-restart $DOCK_PREF
$DOCK_UTIL --remove "iTunes" --no-restart $DOCK_PREF
$DOCK_UTIL --remove "iBooks" --no-restart $DOCK_PREF


# Kill the dock so it will relaunch with our added content.
sleep 5
killall Dock

exit 0;
