#!/bin/bash

# Get current user
currentUser=`python -c 'from SystemConfiguration import SCDynamicStoreCopyConsoleUser; import sys; username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]; username = [username,""][username in [u"loginwindow", None, u""]]; sys.stdout.write(username + "\n");'`

# Set screensaver time for current user to 1 hour, outside the 30-min auto-logout time so it doesn't obscure that message.
su $currentUser -c "/usr/bin/defaults -currentHost write com.apple.screensaver idleTime 3600"

# Force restart of preferences service
killall cfprefsd

exit 0;
