#!/bin/bash

###############################################################################
#
# Schedule a time for a Mac to wake up overnight.
#
# This script expects to be run from a JAMF JSS. It allows the randomisation
# of the wake time witin a range of minutes, starting at a particular time.
#
# It takes three arguments:
# 
# $4: Days - this should be in the format expected by the `pmset`
#     command, ie a subset pf MTWRFSU
#
# $5: Randomise start time - this is the time (HH:MM) that will be 
#     used as the starting point for the interval during which a
#     a wake might occur
#
# $6: Randomise interval - a number of minutes which provde an interval
#     after the start time, during which a wake will be scheduled to happen
#
# EXAMPLE: to set machines to wake between 1am and 3.30am every morning, 
# you would give the following arguments:
# 
# $4 = MTWRFSU
# $5 = 01:00
# $6 = 150 (150 minutes = 2.5 hours)
# 
####
# Date: @@DATE
# Version: @@VERSION
# Origin: @@ORIGIN
# Link: @@ORIGIN/commit/@@VERSION
#
# Released by JSS User: @@USER
#################################################################################
set -ueo pipefail

days="$4"
randomise_time_start="$(echo "${5}" | sed -E 's/://g')"
randomise_interval_minutes="${6}"

minute_offset=$(jot -r 1 0 "${randomise_interval_minutes}")

# Generate start time using the date commend to add the offset minutes
# to the specififed start time.
restart_time="$(date -j -v +"${minute_offset}"M "${randomise_time_start}" +%H:%M:00)"

if pmset repeat wake "${days}" "${restart_time}"
then
    echo "Restart set for ${restart_time} on ${days}"
    exit 0
else
    echo "Failed to set restart for ${restart_time} on ${days}"
    exit 1
fi

